print('=' * 70)
print(' Tavily AI 搜索引擎 - 安装成功')
print('=' * 70)
print()
print('使用方法:')
print('  1. 访问 https://tavily.com 注册获取免费 API Key')
print('  2. 设置环境变量: set TAVILY_API_KEY=your_key_here')
print('  3. 运行: python tavily_search.py "你的搜索词"')
print()
print('特点:')
print('  - AI 驱动的搜索引擎')
print('  - 自动生成答案摘要')
print('  - 支持深度搜索模式')
print('  - 免费版每月 1000 次搜索')
print()
print('示例:')
print('  python tavily_search.py "佳缘科技 301117 最新消息"')
print('  python tavily_search.py "Python 股票分析教程"')
print('=' * 70)
